apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: default
  name: cron-ecr-credentials-renew
  labels:
    app: ecr-credentials-renew
spec:
  schedule: "0 */8 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: svc-ecr-credentials-renew
          containers:
            - name: ecr-renew
              image: nabsul/k8s-ecr-login-renew:latest
              env:
                - name: DOCKER_SECRET_NAME
                  value: ecr-docker-credentials
                - name: TARGET_NAMESPACE
                  value: default
                - name: AWS_REGION
                  valueFrom:
                    secretKeyRef:
                      name: ecr-credentials-secret
                      key: REGION
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: ecr-credentials-secret
                      key: ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: ecr-credentials-secret
                      key: SECRET
