apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: svc-ecr-credentials-renew
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: role-ecr-credentials-renew
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: rolebinding-ecr-credentials-renew
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-ecr-credentials-renew
subjects:
  - kind: ServiceAccount
    name: svc-ecr-credentials-renew
    namespace: default
